# Autogenerated by devscripts/update-version.py

__version__ = '2025.05.28.152430'

RELEASE_GIT_HEAD = '26d5a53c7662657061ac41fe4b6415ce210aa614'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yt-dlp/yt-dlp-nightly-builds'

ORIGIN = 'gamer191/yt-dlp'

_pkg_version = '2025.05.28.152430'
