# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.10.132206'

RELEASE_GIT_HEAD = '6fff03787817c79f3f86e54c4aaa835c6ed2ef70'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yt-dlp/yt-dlp-nightly-builds'

ORIGIN = 'gamer191/yt-dlp'

_pkg_version = '2025.10.10.132206'
