# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.21'

RELEASE_GIT_HEAD = 'ecf2cbf04b2fec4336bef08d0773df88654f27ee'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yt-dlp/yt-dlp-nightly-builds'

ORIGIN = 'gamer191/yt-dlp'

_pkg_version = '2025.03.21'
