name: Build Artifacts
on:  workflow_dispatch

permissions:
  contents: read

jobs:
  unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge
          auto-update-conda: true
          activate-environment: ""
          auto-activate-base: false
      - name: Install Requirements
        run: |
          sudo apt -y install zip pandoc man sed
          cat > ./requirements.txt << EOF
          python=3.10.*
          pyinstaller
          brotli-python
          EOF
          python devscripts/install_deps.py --print \
            --exclude brotli --exclude brotlicffi \
            --include secretstorage >> ./requirements.txt
          mamba create -n build --file ./requirements.txt

      - name: Prepare
        run: |
          python devscripts/update-version.py -c "stable" -r "gamer191/yt-dlp" "2024.04.27"
          python devscripts/update_changelog.py -vv
          python devscripts/make_lazy_extractors.py
      - name: Build Unix standalone binary
        shell: bash -l {0}
        run: |
          unset LD_LIBRARY_PATH  # Harmful; set by setup-python
          conda activate build
          python -m bundle.pyinstaller --onedir
          mv ./dist/yt-dlp_linux ./yt-dlp_linux

      - name: Verify --update-to
        run: |
         chmod +x ./yt-dlp_linux
         ./yt-dlp_linux --version
