name: test on macos-13
on: workflow_dispatch
jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        executable: [yt-dlp_macos,yt-dlp_macos_legacy]
    
    steps:
    - run: |
        curl -L https://github.com/gamer191/yt-dlp/releases/download/macos-14-test/${{ matrix.executable }} -o ~/.local/bin/yt-dlp
        chmod a+rx ~/.local/bin/yt-dlp  # Make executable
        yt-dlp --verbose
        yt-dlp --update-to yt-dlp/yt-dlp@latest
        yt-dlp --verbose
