name: Build Artifacts
on:  workflow_dispatch

jobs:
  unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge
          auto-update-conda: true
          activate-environment: ""
          auto-activate-base: false
      - name: Install Requirements
        run: |
          sudo apt -y install pandoc
          mamba create -n build python=3.10.* pyinstaller brotli-python certifi mutagen pycryptodomex "requests>=2.31.0,<3" "urllib3>=1.26.17,<3" "websockets>=12.0" cffi
      - name: Build Unix standalone binary
        shell: bash --login {0}
        run: |
          unset LD_LIBRARY_PATH  # Harmful; set by setup-python
          conda activate build
          python -m bundle.pyinstaller --onedir

      - name: Verify --update-to
        run: |
         chmod +x ./dist/yt-dlp_linux/yt-dlp_linux
         ./dist/yt-dlp_linux/yt-dlp_linux --version
