name: Core Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    name: Core Tests
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        protobuf: ['IIAQ', 'IIAg', 'IIAw', 'IIBA', 'IIBQ', 'IIBg', 'IIBw', 'IICA', 'IICQ', 'IQAQ', 'IQAg', 'IQAw', 'IQBA', 'IQBQ', 'IQBg', 'IQBw', 'IQCA', 'IQCQ', 'IYAQ', 'IYAg', 'IYAw', 'IYBA', 'IYBQ', 'IYBg', 'IYBw', 'IYCA', 'IYCQ', 'IgAQ', 'IgAg', 'IgAw', 'IgBA', 'IgBQ', 'IgBg', 'IgBw', 'IgCA', 'IgCQ', 'IoAQ', 'IoAg', 'IoAw', 'IoBA', 'IoBQ', 'IoBg', 'IoBw', 'IoCA', 'IoCQ', 'IwAQ', 'IwAg', 'IwAw', 'IwBA', 'IwBQ', 'IwBg', 'IwBw', 'IwCA', 'IwCQ', 'I4AQ', 'I4Ag', 'I4Aw', 'I4BA', 'I4BQ', 'I4Bg', 'I4Bw', 'I4CA', 'I4CQ', 'JAAQ', 'JAAg', 'JAAw', 'JABA', 'JABQ', 'JABg', 'JABw', 'JACA', 'JACQ', 'JIAQ', 'JIAg', 'JIAw', 'JIBA', 'JIBQ', 'JIBg', 'JIBw', 'JICA', 'JICQ']
        attempt: [1,2,3]
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      continue-on-error: False
      run: |
        sed -i 's/IIAQ/${{ matrix.protobuf }}/g' yt_dlp/extractor/youtube.py
        git diff
        python3 -Werror -m yt_dlp --simulate --extractor-args "youtube:player_client=android" --abort-on-error WNCl-69POro
