name: Core Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    name: Core Tests
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        protobuf: ['CgIIAQ', 'CgIIAg', 'CgIIAw', 'CgIIBA', 'CgIIBQ', 'CgIIBg', 'CgIIBw', 'CgIICA', 'CgIICQ', 'CgIQAQ', 'CgIQAg', 'CgIQAw', 'CgIQBA', 'CgIQBQ', 'CgIQBg', 'CgIQBw', 'CgIQCA', 'CgIQCQ', 'CgIYAQ', 'CgIYAg', 'CgIYAw', 'CgIYBA', 'CgIYBQ', 'CgIYBg', 'CgIYBw', 'CgIYCA', 'CgIYCQ', 'CgIgAQ', 'CgIgAg', 'CgIgAw', 'CgIgBA', 'CgIgBQ', 'CgIgBg', 'CgIgBw', 'CgIgCA', 'CgIgCQ', 'CgIoAQ', 'CgIoAg', 'CgIoAw', 'CgIoBA', 'CgIoBQ', 'CgIoBg', 'CgIoBw', 'CgIoCA', 'CgIoCQ', 'CgIwAQ', 'CgIwAg', 'CgIwAw', 'CgIwBA', 'CgIwBQ', 'CgIwBg', 'CgIwBw', 'CgIwCA', 'CgIwCQ', 'CgI4AQ', 'CgI4Ag', 'CgI4Aw', 'CgI4BA', 'CgI4BQ', 'CgI4Bg', 'CgI4Bw', 'CgI4CA', 'CgI4CQ', 'CgJAAQ', 'CgJAAg', 'CgJAAw', 'CgJABA', 'CgJABQ', 'CgJABg', 'CgJABw', 'CgJACA', 'CgJACQ', 'CgJIAQ', 'CgJIAg', 'CgJIAw', 'CgJIBA', 'CgJIBQ', 'CgJIBg', 'CgJIBw', 'CgJICA', 'CgJICQ', 'EgIIAQ', 'EgIIAg', 'EgIIAw', 'EgIIBA', 'EgIIBQ', 'EgIIBg', 'EgIIBw', 'EgIICA']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install test requirements
      run: python3 ./devscripts/install_deps.py --include dev --include curl_cffi
    - name: Run tests
      continue-on-error: False
      run: |
        sed -i 's/CgIIAQ/${{ matrix.protobuf }}/g' yt_dlp/extractor/youtube.py
        python3 -Werror -m yt_dlp --simulate WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro WNCl-69POro --extractor-args "youtube:player_client=android" 
