name: Core Tests
on: push
  
jobs:
  tests:
    name: Install cffi
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        command: [python3 -m pip install cffi,Py_GIL_DISABLED=0 python3 -m pip install cffi]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14.0-beta.1'
    - run: ${{ matrix.command }}
