name: Quick Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  check:
    name: Code check
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.9', 'pypy-3.10', 'pypy-3.11']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dev dependencies
      run: python3 ./devscripts/install_deps.py -o --include static-analysis
    - name: Make lazy extractors
      run: python3 ./devscripts/make_lazy_extractors.py
    - name: Run ruff
      run: ruff check --output-format github .
    - name: Run pycodestyle
      run: pycodestyle yt_dlp/extractor/bilibili.py --select=E231
    - name: Check file mode
      run: git ls-files --format="%(objectmode) %(path)" yt_dlp/ | ( ! grep -v "^100644" )
