name: test-linux
on: push
jobs:
  cmd-tests:
    name: test-linux
    runs-on: ubuntu-latest
    steps:
    - run: curl https://github.com/yt-dlp/yt-dlp/releases/download/2025.08.20/yt-dlp_linux -o yt-dlp_linux --location
    - run: chmod 777 yt-dlp_linux
    - run: ./yt-dlp_linux --verbose --update-to nightly
    - run: ./yt-dlp_linux --verbose --update-to master
    - run: ./yt-dlp_linux --verbose --update-to stable