name: test-truthsocial
on: [workflow_dispatch, push]
jobs:
  tests:
    name: ${{ matrix.program }} (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11-dev']
        program: ['yt-dlp']
    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.program }}
      run: pip install ${{ matrix.program }}
    - name: Run tests
      run: ${{ matrix.program }} "https://truthsocial.com/@KarliBonne/posts/110319486893480616" --list-formats --print-traffic
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://truthsocial.com/api/v1/statuses/110319486893480616 -H "User-Agent:hello"
